GET http://localhost:3000/users

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/1

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "nickname": "gorae",
  "password": "1234",
  "confirm": "1234"
}

###

POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "cat",
  "content": "is cute",
  "userId": 1
}
###

PATCH  http://localhost:3000/posts/1
Content-Type: application/json

{
  "content": "is perfect"
}
###

DELETE http://localhost:3000/posts/1

