GET http://localhost:3000/users

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/comments/

###
GET http://localhost:3000/posts/1

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "nickname": "gorae",
  "password": "1234",
  "confirm": "1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "nickname": "gorae",
  "password": "1234"
}

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDQyOTUyfQ.Pm8s-2iOoNNlFP2Ox-9WQBzsQINjKQDcR5jbLFV6agE

{
  "title": "cats",
  "content": "are fat"
}
###

PATCH  http://localhost:3000/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDQyOTUyfQ.Pm8s-2iOoNNlFP2Ox-9WQBzsQINjKQDcR5jbLFV6agE

{
  "content": "are best"
}
###

DELETE http://localhost:3000/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDQyOTUyfQ.Pm8s-2iOoNNlFP2Ox-9WQBzsQINjKQDcR5jbLFV6agE

###

POST http://localhost:3000/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ

{
  "content": "I like cat"
}

###

PATCH  http://localhost:3000/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ

{
  "content": "lovely cat"
}

###

DELETE http://localhost:3000/comments/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ