GET http://localhost:3000/users

###
GET http://localhost:3000/api/posts/
###
GET http://localhost:3000/api/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImtpdHRlbiIsImlhdCI6MTY3NDI3MjE4N30.W9o1GYxHi1Q_DUiOAn3j8xsP4AdovyWlLymx1RswSoE


###
GET http://localhost:3000/comments/

###
GET http://localhost:3000/posts/


###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "nickname": "kitten",
  "password": "1234",
  "confirm": "1234"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "nickname": "gorae",
  "password": "1234"
}

###

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImtpdHRlbiIsImlhdCI6MTY3NDI3MjE4N30.W9o1GYxHi1Q_DUiOAn3j8xsP4AdovyWlLymx1RswSoE

{
  "title": "고양이",
  "content": "귀여워"
}
###

PATCH  http://localhost:3000/api/posts/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0Mjc1OTk4fQ.VERSySeXUC0QHCrZMioTcUQIKITbDmVKXYd5coYVTjk

{
  "content": "고양이 만세!"
}
###

DELETE http://localhost:3000/api/posts/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDQyOTUyfQ.Pm8s-2iOoNNlFP2Ox-9WQBzsQINjKQDcR5jbLFV6agE

###

POST http://localhost:3000/posts/5/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImtpdHRlbiIsImlhdCI6MTY3NDEzMjAxMX0.7U4Uajclq7D6VRQgOgxXuWnaqAFxXKMZwpLwCDoCVlg



###

POST http://localhost:3000/comments/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ

{
  "content": "I like cat"
}

###

PATCH  http://localhost:3000/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ

{
  "content": "lovely cat"
}

###

DELETE http://localhost:3000/comments/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImdvcmFlIiwiaWF0IjoxNjc0MDUwMTA4fQ.q9VyKjYsvCUnfDGXdswM6kN6ZNXRqv0GpzIcaD0rGdQ